title: "Aleksandr S"
logo: "/images/logo.png?raw=true"
description:
  <div>
    <br>
    <h2>Expertise React developer with 5 years of experience</h2>
    <br>
    <!--
      PeoplePerHour Profile Widget
      The div#pph-hire me is the element
      where the iframe will be inserted.
      You may move this element wherever
      you need to display the widget
    -->
    <div id="pph-hireme"></div>
  </div>
google_analytics: UA-00000-0
theme: jekyll-theme-minimal
