title: "Aleksandr S"
logo: "/images/logo.png?raw=true"
description:
  <div>
    <br>
    <h3>Expertise React developer with 5 years of experience</h3>
    <br>
    Senior React developer specializing in web development. Knowledgeable of all the development cycle stages and have a good command of coding languages. I have much experience in teamwork and excellent problem-solving skills.
    <br><br>
    <a href="https://www.linkedin.com/in/oleksandr-simakovych-ab2b75183/ ">LinkedIn</a>
  </div>
google_analytics: UA-00000-0
theme: jekyll-theme-minimal
