title: "Aleksandr S"
logo: "/images/logo.png?raw=true"
description:
  Expertise React developer with 5 years of experience
  <br><br>
  Senior React developer specializing in web development. Knowledgeable of all the development cycle stages and have a good command of coding languages. I have much experience in teamwork and excellent problem-solving skills.
  <br><br>
  <a href="">View My LinkedIn Profile</a>
google_analytics: UA-00000-0
theme: jekyll-theme-minimal
