title: "Aleksandr S"
logo: "/images/logo.png?raw=true"
description:
  <div>
    <br>
    <h3>Expertise React developer with 5 years of experience</h3>
    <br>
    Senior React developer specializing in web development. Knowledgeable of all the development cycle stages and have a good command of coding languages. I have much experience in teamwork and excellent problem-solving skills.
    <br><br>
    <a href="https://www.linkedin.com/in/oleksandr-simakovych-ab2b75183/ ">LinkedIn</a>
    <!--
      PeoplePerHour Profile Widget
      The div#pph-hire me is the element
      where the iframe will be inserted.
      You may move this element wherever
      you need to display the widget
    -->
    <div id="pph-hireme"></div>
    <script type="text/javascript">
    (
      function(d, s) {
        var useSSL = 'https:' == document.location.protocol;
        var js, where = d.getElementsByTagName(s)[0],
        js = d.createElement(s);
        js.src = (useSSL ? 'https:' : 'http:') +  '//www.peopleperhour.com/hire/2369245691/2769584.js?width=300&height=135&orientation=vertical&theme=dark&rnd='+parseInt(Math.random()*10000, 10);
        try { where.parentNode.insertBefore(js, where); } catch (e) { if (typeof console !== 'undefined' && console.log && e.stack) { console.log(e.stack); } }
      } (document, 'script')
    );
    </script>
  </div>
google_analytics: UA-00000-0
theme: jekyll-theme-minimal
