title: Aleksandr S
logo: "/images/logo.png?raw=true"
description: >
  First Description
  <br><br>
  Second Description
  <br><br>
  <a href="">View My LinkedIn Profile</a>
  <div id="pph-hireme"></div>
  <script type="text/javascript">
  (function(d, s) {
    var useSSL = 'https:' == document.location.protocol;
    var js, where = d.getElementsByTagName(s)[0],
    js = d.createElement(s);
    js.src = (useSSL ? 'https:' : 'http:') +  '//www.peopleperhour.com/hire/2369245691/2769584.js?width=300&height=135&orientation=vertical&theme=dark&rnd='+parseInt(Math.random()*10000, 10);
    try { 
      where.parentNode.insertBefore(js, where); 
    } 
    catch (e) { 
      if (typeof console !== 'undefined' && console.log && e.stack) { 
        console.log(e.stack); 
      } 
    }
  }(document, 'script'));
  </script>
 theme: jekyll-theme-minimal
 google_analytics: UA-00000-0
